#!/usr/bin/env bash
#
# A wizard — walks a human through setting up the Vault developer environment.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _ensure_cargo_path — ensure Rust/cargo binary paths are included in PATH
_ensure_cargo_path() {
  local candidate
  local candidates=("$HOME/.cargo/bin")
  if [[ -n "${USERPROFILE:-}" ]]; then
    candidates+=("$USERPROFILE/.cargo/bin")
    if command -v cygpath >/dev/null 2>&1; then
      candidates+=("$(cygpath -u "$USERPROFILE/.cargo/bin" 2>/dev/null || echo "")")
    fi
  fi
  for candidate in "${candidates[@]}"; do
    if [[ -n "$candidate" && -d "$candidate" ]] && [[ ":$PATH:" != *":$candidate:"* ]]; then
      export PATH="$candidate:$PATH"
    fi
  done
}

_ensure_cargo_path

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard guides you step-by-step through configuring prerequisites,\n' "$DIM"
  printf '  dependencies, and build tools required for developing Vault locally.\n'
  printf '  Stop any time with Ctrl-C and re-run later.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Vault setup complete!%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Vault — Local Developer Environment Setup"

# ── Stage 1: Node.js & Package Manager ────────────────────────────────────
stage "Node.js & Package Manager"
say "Vault requires Node.js (v18.0.0 or higher) and npm."

if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
  NODE_VER=$(node -v)
  NPM_VER=$(npm -v)
  say "✓ Node.js ($NODE_VER) and npm ($NPM_VER) are installed."
else
  warn "Node.js or npm is missing!"
  step "Open https://nodejs.org/ to download and install Node.js (LTS version recommended)."
  open_url "https://nodejs.org/"
  pause "Press Enter after completing Node.js installation."
fi

# ── Stage 2: Rust Toolchain Setup ──────────────────────────────────────────
stage "Rust Toolchain Setup"
say "Tauri v2 requires the Rust compiler (cargo/rustc)."

_ensure_cargo_path

if command -v rustc >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
  RUST_VER=$(rustc --version)
  say "✓ Rust toolchain found: $RUST_VER"
else
  warn "Rust toolchain is not detected in your PATH."
  step "Install rustup from https://rustup.rs/"
  open_url "https://rustup.rs/"
  step "Follow the installation prompts for rustup-init."
  pause "Press Enter after completing Rust toolchain installation."
  _ensure_cargo_path
  if command -v rustc >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
    RUST_VER=$(rustc --version)
    say "✓ Rust toolchain verified: $RUST_VER"
  else
    warn "Rust toolchain was still not found in PATH. Desktop dev mode requires Rust."
  fi
fi

# ── Stage 3: OS Native Build Tools ────────────────────────────────────────
stage "OS Native Build Tools"
say "Tauri requires platform-specific native C++ build tools."

OS_TYPE="$(uname -s 2>/dev/null || echo "Windows")"
case "$OS_TYPE" in
  Linux*)
    say "On Linux (Ubuntu/Debian), ensure required development packages are installed:"
    note "  sudo apt update && sudo apt install -y build-essential curl libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev"
    if confirm "Run apt install now?"; then
      sudo apt update && sudo apt install -y build-essential curl libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev || warn "apt install failed or skipped"
    fi
    ;;
  Darwin*)
    say "On macOS, Xcode Command Line Tools are required."
    if ! xcode-select -p >/dev/null 2>&1; then
      warn "Xcode CLI tools missing. Run: xcode-select --install"
      step "Installing Xcode Command Line Tools..."
      xcode-select --install || true
      pause "Press Enter when Xcode tools installation completes."
    else
      say "✓ Xcode Command Line Tools detected."
    fi
    ;;
  *)
    say "On Windows, Visual Studio C++ Build Tools and WebView2 are required."
    step "Install 'Desktop development with C++' workload via Visual Studio Installer."
    if ! confirm "Are Microsoft Visual C++ Build Tools already installed?"; then
      open_url "https://visualstudio.microsoft.com/visual-cpp-build-tools/"
      pause "Press Enter after completing Visual Studio C++ Build Tools setup."
    fi
    ;;
esac

# ── Stage 4: Install Dependencies & Git Hooks ─────────────────────────────
stage "Install Dependencies & Git Hooks"
say "Installing npm packages and setting up Husky git hooks..."

if confirm "Run 'npm install' now?"; then
  npm install
  say "✓ npm dependencies installed."
fi

if confirm "Run 'npm run prepare' to initialize Husky git hooks?"; then
  npm run prepare || warn "Husky setup skipped or failed."
fi

# ── Stage 5: Environment Configuration ────────────────────────────────────
stage "Environment Configuration"
say "Configuring local environment settings."

ask VITE_PORT "Preferred Vite dev server port (default: 5173):"
VITE_PORT="${VITE_PORT:-5173}"
write_env VITE_PORT "$VITE_PORT"

ask VITE_APP_TITLE "App Title for local dev (default: Vault):"
VITE_APP_TITLE="${VITE_APP_TITLE:-Vault}"
write_env VITE_APP_TITLE "$VITE_APP_TITLE"

# ── Stage 6: Verification & First Launch ──────────────────────────────────
stage "Verification & First Launch"
say "Running quick checks to verify your environment."

if confirm "Run TypeScript compilation check (npx tsc --noEmit)?"; then
  npx tsc --noEmit && say "✓ TypeScript check passed!" || warn "TypeScript check reported errors."
fi

if confirm "Run test suite (npx vitest run)?"; then
  npx vitest run && say "✓ Vitest test suite passed!" || warn "Vitest tests failed."
fi

if confirm "Launch Vault Desktop Dev Mode now (npm run tauri dev)?"; then
  _ensure_cargo_path
  if command -v cargo >/dev/null 2>&1; then
    say "Starting Tauri dev server..."
    npm run tauri dev
  else
    warn "Cargo is not found in PATH. Cannot start Tauri dev server."
    if confirm "Fallback to Web UI Dev Server instead (npm run dev)?"; then
      say "Starting Vite dev server..."
      npm run dev
    fi
  fi
elif confirm "Launch Web UI Dev Server instead (npm run dev)?"; then
  say "Starting Vite dev server..."
  npm run dev
fi

# ──────────────────────────────────────────────────────────────────────────

finish
